lib/lunchmoney/categories/category.rb, lib/lunchmoney/categories/category_calls.rb, lib/lunchmoney/data_object.rb, lib/lunchmoney/exceptions.rb, test/helpers/fake_response_data_helper.rb, test/lunchmoney/categories/category_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/105
=> complete all_categories call

Gemfile.lock, lib/lunchmoney/version.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/120
=> update gem version to 0.5.1

lib/lunchmoney/plaid_accounts/plaid_account.rb, test/helpers/fake_response_data_helper.rb, test/lunchmoney/plaid_accounts/plaid_account_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/98
=> finish plaid_accounts call

lib/lunchmoney/api.rb, lib/lunchmoney/api_call.rb, lib/lunchmoney/plaid_accounts/plaid_account_calls.rb, test/lunchmoney/plaid_accounts/plaid_account_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/131
=> Add plaid accounts fetch

lib/lunchmoney/api.rb, lib/lunchmoney/tags/tag_calls.rb, test/cassettes/tags/tags_success.yml, test/helpers/environment_helper.rb, test/lunchmoney/configuration_test.rb, test/lunchmoney/plaid_accounts/plaid_account_calls_test.rb, test/lunchmoney/tags/tag_calls_test.rb, test/test_helper.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/92 and resolves https://github.com/halorrr/lunchmoney-ruby/issues/93
=> Get tags calls working

lib/lunchmoney/api.rb, lib/lunchmoney/user/user_calls.rb, test/cassettes/user/me_success.yml, test/lunchmoney/user/user_calls_test.rb, test/test_helper.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/80 and resolves https://github.com/halorrr/lunchmoney-ruby/issues/81
=> finish user calls

lib/lunchmoney/crypto/crypto.rb, lib/lunchmoney/crypto/crypto_calls.rb, test/cassettes/crypto/crypto_success.yml, test/lunchmoney/crypto/crypto_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/101 and contributes to https://github.com/halorrr/lunchmoney-ruby/issues/103
=> finish main crypto call

lib/lunchmoney/crypto/crypto.rb, test/lunchmoney/crypto/crypto_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/104
=> add validations to crypto object

lib/lunchmoney/budget/budget.rb, test/cassettes/budget/budgets_success.yml
After adding a recurring expense, the budget object broke because an undocumented recurring field appeared on the budget object returned from the API
=> add recurring field to budget object

lib/lunchmoney/recurring_expenses/recurring_expense.rb, test/cassettes/recurring_expenses/recurring_expenses_success.yml, test/lunchmoney/recurring_expenses/recurring_expense_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/95 and resolves https://github.com/halorrr/lunchmoney-ruby/issues/96
=> get recurring_expense calls working

lib/lunchmoney/api.rb, lib/lunchmoney/categories/category.rb, lib/lunchmoney/categories/category_calls.rb, lib/lunchmoney/categories/child_category.rb, test/cassettes/categories/category_category_group_success.yml, test/cassettes/categories/category_category_success.yml, test/cassettes/categories/category_does_not_exist_failure.yml, test/lunchmoney/categories/category_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/106
=> support single category calls

lib/lunchmoney/tags/tag_calls.rb, lib/lunchmoney/tags/transaction_tag.rb, lib/lunchmoney/transactions/child_transaction.rb, lib/lunchmoney/transactions/transaction.rb, lib/lunchmoney/transactions/transaction_calls.rb, test/cassettes/transactions/transactions_success.yml, test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/83
=> get transactions call working

lib/lunchmoney/api.rb, lib/lunchmoney/transactions/transaction_calls.rb, test/cassettes/transactions/transaction_success.yml, test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/84
=> support single transaction calls

lib/lunchmoney/api.rb, lib/lunchmoney/transactions/transaction_calls.rb, test/cassettes/transactions/transaction_group_success.yml, test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/148
=> support getting a transaction group

test/lunchmoney/plaid_accounts/plaid_account_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/154
=> fix flakey plaid accounts fetch test

lib/lunchmoney/api_call.rb, lib/lunchmoney/budget/budget_calls.rb, lib/lunchmoney/categories/category_calls.rb, lib/lunchmoney/crypto/crypto_calls.rb, lib/lunchmoney/plaid_accounts/plaid_account_calls.rb, lib/lunchmoney/recurring_expenses/recurring_expense_calls.rb, lib/lunchmoney/transactions/transaction_calls.rb, test/lunchmoney/api_call_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/146
=> add helper for clean params

.github/workflows/ci.yml, .rubocop.yml, lunchmoney-ruby.gemspec
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/114
=> add ruby 3.1 to 3.3 ruby support

Appraisals, Gemfile.lock, lib/lunchmoney/version.rb, lunchmoney-ruby.gemspec
Working toward https://github.com/halorrr/lunchmoney-ruby/issues/115
need to publish a new version with lower requirements to properly test appraisals
=> Test against multiple dependencies

lib/lunchmoney/transactions/transaction_calls.rb, test/cassettes/transactions/unsplit_transaction_success.yml, test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/87
=> finish unsplit transaction call

lib/lunchmoney/transactions/transaction_calls.rb, test/cassettes/transactions/create_transaction_group_success.yml, test/cassettes/transactions/delete_transaction_group_success.yml, test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/88
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/89
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/90
=> finish create and delete transaction group

test/lunchmoney/transactions/transaction_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/169
=> don't use ci remote call on insert_transaction

lib/lunchmoney/api_call.rb, lib/lunchmoney/budget/budget_calls.rb, test/cassettes/budget/remove_budgett_success.yml, test/lunchmoney/budget/budget_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/70 and resolves https://github.com/halorrr/lunchmoney-ruby/issues/71
=> finish remove_budget call

lib/lunchmoney/categories/category_calls.rb, test/cassettes/categories/add_to_category_group_success.yml, test/cassettes/categories/create_category_group_success.yml, test/cassettes/categories/create_category_success.yml, test/cassettes/categories/delete_category_success.yml, test/cassettes/categories/force_delete_category_success.yml, test/cassettes/categories/update_category_success.yml, test/lunchmoney/categories/category_calls_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/180
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/107
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/108
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/109
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/110
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/111
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/112
=> finish remaining category endpoints

.github/workflows/ci.yml
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/171
=> add daily schedule to CI

.rubocop.yml, Gemfile.lock, README.md, bin/console, lib/lunchmoney-ruby.rb, lunchmoney.gemspec, test/test_helper.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/173
=> update gem name to lunchmoney

sorbet/rbi/gems/activesupport@7.1.3.rbi, test/vcr_test.rb
Resolves https://github.com/halorrr/lunchmoney-ruby/issues/170
=> add warning when cassette is older than 30 days

lib/lunchmoney/api.rb, lib/lunchmoney/objects/asset.rb, test/cassettes/assets/create_asset_success.yml, test/cassettes/assets/update_asset_success.yml, test/lunchmoney/calls/assets_test.rb
Resolves https://github.com/halorrr/lunchmoney/issues/195 and resolves https://github.com/halorrr/lunchmoney/issues/196
=> add missing tests and docs for asset calls

.github/workflows/check_pipeline.yml, .github/workflows/ci.yml, .github/workflows/release_pipeline.yml, .simplecov, .toys/.toys.rb, .toys/coverage.rb, Gemfile, Gemfile.lock, test/test_helper.rb
Resolves https://github.com/mmenanno/lunchmoney/issues/211
=> add simplecov

.github/workflows/check_pipeline.yml, .github/workflows/rbi-updater.yml
This should fix a few errors, and allow this workflow to also help on regular PRs
=> make rbi updater more generalized

.simplecov, lib/lunchmoney/api.rb, lib/lunchmoney/deprecate.rb, test/helpers/deprecation_helper.rb, test/lunchmoney/deprecate_test.rb, test/test_helper.rb
Resolves https://github.com/mmenanno/lunchmoney/issues/333
=> add module for deprecation handling

Gemfile.lock, lib/lunchmoney/version.rb
This PR bumps the gem version from 1.4.1 to 1.5.0.
- ✨ **New Features**: Memory optimization for large collections, per-request validation configuration, deprecation module
- 🚀 **Performance**: Connection reuse with FlatParamsEncoder, optimized object serialization, improved ActiveSupport dependency loading
- 🔧 **Improvements**: Better API response handling pattern, reduced API delegation duplication
- 🛡️ **Security**: Comprehensive security policy added
- 📦 **Infrastructure**: Ruby 3.4.5 support, dependency updates, migrated from CodeClimate to Qlty.sh
This is a minor version bump as it includes new features and performance improvements without breaking changes.
Ready for merge and release as v1.5.0.
=> Bump version to 1.5.0

.github/workflows/build_and_publish_yard_docs.yml, .github/workflows/check_pipeline.yml, .github/workflows/ci.yml, .github/workflows/performance-monitor.yml, .github/workflows/rbi-updater.yml, .github/workflows/release_pipeline.yml, .github/workflows/security-audit.yml
This PR implements comprehensive optimizations and enhancements to the GitHub workflows based on performance analysis and best practices.
- **Job Parallelization**: Split CI into separate  and  jobs that run in parallel
- **Comprehensive Caching**: Added caching for gems, RBI files, VCR cassettes, and YARD documentation
- **Matrix Strategy Refinement**: Improved Ruby version testing with proper experimental handling
- **Expected Performance Gain**: 25-35% faster CI runs
- Updated `ruby/setup-ruby@v1.218.0` → `ruby/setup-ruby@v1`
- Replaced outdated `ad-m/github-push-action@v0.8.0` with native `git push`
- Standardized Ruby version to `3.4` across workflows
- Added proper `permissions` blocks to all workflows
- Enhanced RBI updater with safety checks and change detection
- Maintained …
=> feat: optimize and enhance GitHub workflows
